version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: echo $KEY_PROPERTIES | base64 --decode > ./android/key.properties
      - run: flutter doctor
        #      - run: flutter test
      - run: flutter -v build apk
      - store_artifacts:
          path: /home/cirrus/project/build/app/outputs/apk/release/app-release.apk
          destination: telara-mobile_release.apk
